# Generated by Django 3.1.8 on 2021-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_auto_20210318_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='robbery_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='date_of_robbery',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
