# Generated by Django 3.1.8 on 2021-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_auto_20210421_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='bike',
            name='date_of_robbery',
            field=models.DateTimeField(null=True),
        ),
    ]
