# Generated by Django 3.1.8 on 2021-06-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_auto_20210602_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='name',
        ),
    ]
