# Generated by Django 3.1.8 on 2021-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_remove_bike_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='geographic_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
