# Generated by Django 3.1.9 on 2021-09-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_auto_20210608_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='circumstances',
            field=models.TextField(blank=True, null=True),
        ),
    ]
